version: '3.8'

services:
  claim-backend:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    ports:
      - "3000:3000"
