services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass your_redis_password

  claim-backend:
    build:
      context: ./
      dockerfile: dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./files-templates:/app/files-templates
      - ./.env:/app/.env
    ports:
      - "3600:3000"
    environment:
      - NEST_REDIS_HOST=redis
      - NEST_REDIS_PORT=6379
      - NEST_REDIS_PASSWORD=your_redis_password
      - NEST_REDIS_USER=
      - NEST_PORT=3000
    depends_on:
      - redis
  claim-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: claim-database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "2333:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
